export const SET_PRICE_LIMIT = "SET_PRICE_LIMIT";
export const SET_SQUARE_LIMIT = "SET_SQUARE_LIMIT";
export const SET_BEDROOMS_LIMIT = "SET_BEDROOMS_LIMIT";
export const SET_BATHROOMS_LIMIT = "SET_BATHROOMS_LIMIT";
